---

- name: Install Golang
  apt:
    name: golang
    state: present
    install_recommends: false

- name: Copy Golang Profile
  copy:
    src: ./go.cfg
    dest: /etc/runtime/go.cfg
    mode: '0755'

...
