---

- name: Install Ruby
  apt:
    name: ruby
    state: present
    install_recommends: false

- name: Copy Ruby Profile
  copy:
    src: ./ruby.cfg
    dest: /etc/runtime/ruby.cfg
    mode: '0755'

...
