---

- name: Install Erlang
  apt:
    name: erlang
    state: present
    install_recommends: false

- name: Copy Erlang Profile
  copy:
    src: ./erlang.cfg
    dest: /etc/runtime/erlang.cfg
    mode: '0755'

...
