apiVersion: v2
name: leetcode-clone
description: Umbrella chart for leetcode-clone project
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: judge-service
    version: 1.0.0
    condition: judge-service.enabled
  - name: main-backend
    version: 1.0.0
    condition: main-backend.enabled
  - name: main-frontend
    version: 1.0.0
    condition: main-frontend.enabled
  - name: mysql
    repository: https://charts.bitnami.com/bitnami
    version: v12.2.2
    condition: mysql.enabled
  - name: rabbitmq
    repository: https://charts.bitnami.com/bitnami
    version: v15.3.1
    condition: rabbitmq.enabled
