---

- name: Check if NPM is installed
  shell: command -v npm
  register: npm_exists
  ignore_errors: no

- name: Install TypeScript via NPM
  when: npm_exists
  command: npm install -g typescript@=5.7.3

- name: Copy TypeScript Profile
  copy:
    src: ./ts.cfg
    dest: /etc/runtime/ts.cfg
    mode: '0755'

...
