---

- name: Install PHP
  apt:
    name: php
    state: present
    install_recommends: false

- name: Copy PHP Profile
  copy:
    src: ./php.cfg
    dest: /etc/runtime/php.cfg
    mode: '0755'

...
