---

- name: Download Dart SDK
  get_url:
    url: https://storage.googleapis.com/dart-archive/channels/stable/release/latest/linux_packages/dart_3.6.2-1_amd64.deb
    dest: /tmp/dart.deb

- name: Install Dart
  apt:
    deb: /tmp/dart.deb

- name: Cleanup files
  file:
    path: /tmp/dart.deb
    state: absent

...
