replicaCount: 1

image:
  name: leetcode-clone-judge-service
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

securityContext:
  privileged: true
  capabilities:
    add:
      - CAP_SYS_MODULE

env: []

service:
  type: ClusterIP
  port: 8080

resources: {}

livenessProbe:
  httpGet:
    path: /health/liveness
    port: http
  initialDelaySeconds: 5
  timeoutSeconds: 3
  failureThreshold: 10
readinessProbe:
  httpGet:
    path: /health/readiness
    port: http
  initialDelaySeconds: 5
  timeoutSeconds: 3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

volumes:
  - name: cgroup
    hostPath:
      path: /sys/fs/cgroup
      type: Directory

volumeMounts:
  - name: cgroup
    mountPath: /sys/fs/cgroup

nodeSelector: {}

tolerations: []

affinity: {}
