micronaut:
  application:
    name: judge-service
  server:
    port: 8081
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true

  executors:
    judge-listener:
      type: fixed
      n-threads: ${judge.concurrency}

endpoints:
  prometheus:
    enabled: true

rabbitmq:
  uri: ${RABBIT_URL:`amqp://localhost:5672`}
  username: ${RABBIT_USERNAME:`rabbit`}
  password: ${RABBIT_PASSWORD:`secret`}

judge:
  concurrency: 1
  queue:
    feedback: judge.feedback
    submission: judge.submission
