micronaut:
  application:
    name: judge-service
  server:
    host: "0.0.0.0"
  serde:
    serialization:
      inclusion: non_null
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true

  executors:
    judge-listener:
      type: fixed
      n-threads: ${judge.concurrency}

endpoints:
  health:
    details-visible: anonymous
  prometheus:
    sensitive: false
    enabled: true

rabbitmq:
  uri: ${RABBIT_URL:`amqp://localhost:5672`}
  username: ${RABBIT_USERNAME:`guest`}
  password: ${RABBIT_PASSWORD:`guest`}

judge:
  concurrency: 1
  queue:
    feedback: judge.feedback
    submission: judge.submission
