---

- name: Install dependencies
  apt:
    name:
      - build-essential
      - libcap-dev
      - libsystemd-dev
      - pkg-config
    state: present

- name: Checkout Isolate
  git:
    repo: https://github.com/ioi/isolate.git
    dest: /tmp/isolate

- name: Build Isolate
  shell: make isolate install
  args:
    chdir: /tmp/isolate

- name: Cleanup files
  file:
    path: /tmp/isolate
    state: absent

...
