micronaut:
  application:
    name: main-backend
  server:
    host: "0.0.0.0"
  serde:
    serialization:
      inclusion: non_null
  metrics:
    enabled: true
    export:
      prometheus:
      enabled: true
      descriptions: true
      step: PT1M

endpoints:
  health:
    details-visible: anonymous
  prometheus:
    sensitive: false
    enabled: true

datasources:
  default:
    url: ${DATASOURCE_URL:`jdbc:mysql://localhost:3306/main_backend`}
    username: ${DATASOURCE_USERNAME:`main_backend`}
    password: ${DATASOURCE_PASSWORD:`main_backend`}
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema-generate: none
    db-type: mysql
    dialect: MYSQL

liquibase:
  datasources:
     default:
       enabled: true
       changeLog: db/liquibase-changelog.xml

rabbitmq:
  uri: ${RABBIT_URL:`amqp://localhost:5672`}
  username: ${RABBIT_USERNAME:`guest`}
  password: ${RABBIT_PASSWORD:`guest`}

judge:
  queue:
    feedback: judge.feedback
    submission: judge.submission
